guardian/manage-help-content-publisher

build.sbt
legacy-content-import/src/main/scala/legacycontentimport/Article.scala
legacy-content-import/src/main/scala/legacycontentimport/Main.scala

This is to generate a spreadsheet of existing content so that it can be used for more easily batch-setting topics.
Then we can use this to import into SF Knowledge.

Build a CSV list of existing help content

---

legacy-content-import/src/main/scala/legacycontentimport/Article.scala
legacy-content-import/src/main/scala/legacycontentimport/Main.scala

This is to audit the content of the `help` section.
This adds columns for keywords, series, tone and blog to each article.
See also #3.

Add tags to CSV list

---

legacy-content-import/src/main/scala/legacycontentimport/Article.scala

This is a code optimisation.
Previously, the way to tell when to stop loading pages was [when the last page failed to load](https://github.com/guardian/manage-help-content-publisher/blob/main/legacy-content-import/src/main/scala/legacycontentimport/Article.scala#L31).
Now we find out [how many pages there are in all](https://github.com/guardian/manage-help-content-publisher/compare/kc-no-exception?expand=1#diff-d9537d7865d1f49029ebaf513fa80beefc048f2958d0305f8106a956eaf7a601R37) when we load the first page and then [fold over the range of page indices, using the first page of results as the base of the fold](https://github.com/guardian/manage-help-content-publisher/compare/kc-no-exception?expand=1#diff-d9537d7865d1f49029ebaf513fa80beefc048f2958d0305f8106a956eaf7a601R29).

Fetch paginated results without relying on exceptions

---

README.md
build.sbt
legacy-content-import/README.md
legacy-content-import/src/main/resources/import.properties
legacy-content-import/src/main/scala/legacycontentimport/audit/Article.scala
legacy-content-import/src/main/scala/legacycontentimport/audit/Main.scala
legacy-content-import/src/main/scala/legacycontentimport/importer/Article.scala
legacy-content-import/src/main/scala/legacycontentimport/importer/ImportStructure.scala
legacy-content-import/src/main/scala/legacycontentimport/importer/Main.scala
project/Dependencies.scala

This adds a script to generate a zip file for Article Import in Salesforce Knowledge.
It follows the import process described [here](https://help.salesforce.com/articleView?id=sf.knowledge_article_importer.htm).
This script has already been used to import a batch of articles into the Dev org.

Import Capi articles into Salesforce

---

legacy-content-import/src/main/scala/legacycontentimport/importer/ArticleAndTopics.scala
legacy-content-import/src/main/scala/legacycontentimport/importer/ImportStructure.scala
legacy-content-import/src/main/scala/legacycontentimport/importer/Main.scala

We have a script that imports legacy articles from the help section of the main site and generates a zip file from them suitable for importing into Salesforce.
With this change we are able to include topics in the import of articles.
Previously, the Salesforce import file was generated from an input file consisting of line-separated Capi paths.
Eg.
```
help/2021/feb/08/getting-started-with-your-digital-subscription
help/2021/feb/03/id-like-to-make-a-complaint-about-an-advertisement
help/2021/feb/03/what-does-signing-in-mean-for-my-data
```
But now the input file includes the new Help Centre topics for each article, like so:
```
help/2021/feb/08/getting-started-with-your-digital-subscription,The_Guardian_apps
help/2021/feb/03/id-like-to-make-a-complaint-about-an-advertisement,The_Guardian_W …
```

Import topics with articles

---

legacy-content-import/scripts/DeleteAllArticles.apex

This is to clear out all legacy articles in Salesforce before importing live content from Capi.

Add script to delete all articles

---

.github/workflows/snyk.yml

This PR configures a GitHub Action to run Snyk. This action runs every day at 6 AM and on every push. If the branch it's running on is main then it will run `snyk monitor` (reports vulnerabilities to snyk.io), otherwise it will run `snyk test`.
Go to GitHub Action tab to see the result of the Actions run.

Run Snyk as a GitHub Action

---

build.sbt
project/Dependencies.scala
project/plugins.sbt
src/main/scala/managehelpcontentpublisher/Article.scala
src/main/scala/managehelpcontentpublisher/Failure.scala
src/main/scala/managehelpcontentpublisher/Handler.scala
src/main/scala/managehelpcontentpublisher/HtmlToJson.scala
src/main/scala/managehelpcontentpublisher/Topic.scala
src/test/scala/managehelpcontentpublisher/HtmlToJsonTestSuite.scala

This gives a handler that can be run from a [lambda](https://github.com/guardian/manage-help-content-publisher/compare/kc-lambda?expand=1#diff-505c88cfb00274e5b086ed8e0935cef7440b8e4931dd7ad922c2724ba2adead8R16) or [standalone](https://github.com/guardian/manage-help-content-publisher/compare/kc-lambda?expand=1#diff-505c88cfb00274e5b086ed8e0935cef7440b8e4931dd7ad922c2724ba2adead8R35).
It:
1. [takes an article from an API gateway input](https://github.com/guardian/manage-help-content-publisher/compare/kc-lambda?expand=1#diff-505c88cfb00274e5b086ed8e0935cef7440b8e4931dd7ad922c2724ba2adead8R67-R69),
1. [converts the article to an agreed Json format](https://github.com/guardian/manage-help-content-publisher/compare/kc-lambda?expand=1#diff-505c88cfb00274e5b086ed8e0935cef7440b8e4931dd7ad922c2724 …

Create lambda to publish an article

---

build.sbt
project/Dependencies.scala

We're not actually using SLF4J but it's imported with the AWS SDK.
By using a no-op implementation at runtime we get rid of the warning:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Include SLF4J No-op runtime implementation

---

.github/workflows/handle-scala-steward-prs.yml

This change gives us a Github action to test Scala Steward PRs safely outside Teamcity where they might do some damage.

Test PRs raised by Scala Steward

---

cfn.yaml
src/main/scala/managehelpcontentpublisher/Handler.scala

Previously, the stage was hardcoded to `DEV`.  This change reads it from the lambda environment instead or falls back to Dev if running outside a lambda.

Read stage from environment

---

src/main/scala/managehelpcontentpublisher/Article.scala
src/main/scala/managehelpcontentpublisher/Handler.scala
src/main/scala/managehelpcontentpublisher/HtmlToJson.scala
src/main/scala/managehelpcontentpublisher/InputModel.scala
src/main/scala/managehelpcontentpublisher/Topic.scala
src/test/scala/managehelpcontentpublisher/HtmlToJsonTestSuite.scala

We've agreed on an [input model](https://github.com/guardian/manage-help-content-publisher/blob/f7effaf8f6653f3826a945066d60885200c450fd/src/main/scala/managehelpcontentpublisher/InputModel.scala) that gives us all the data we need to publish articles and topics but is not too difficult to generate from Salesforce data.

Modify expected input for publishing lambda to agree with request from Salesforce

---

src/main/scala/managehelpcontentpublisher/Article.scala
src/main/scala/managehelpcontentpublisher/Eithers.scala
src/main/scala/managehelpcontentpublisher/Handler.scala
src/main/scala/managehelpcontentpublisher/HtmlToJson.scala
src/main/scala/managehelpcontentpublisher/InputModel.scala
src/main/scala/managehelpcontentpublisher/PathAndContent.scala
src/main/scala/managehelpcontentpublisher/S3.scala
src/main/scala/managehelpcontentpublisher/SalesforceCleaner.scala
src/main/scala/managehelpcontentpublisher/Topic.scala
src/test/scala/managehelpcontentpublisher/PathAndContentTestSuite.scala

When we publish an Article, we also re-publish the content of the Topics that the Article falls into.  The list of Articles in a Topic is all the published Articles in that Topic ordered by title.
The Topic is published to the S3 bucket `manage-help-content` with key: `<stage>/topics/<topic-path>`.
Content is in the form:
```
{
"path": "...",
"title": "...",
"articles": [
{
"path": "...",
"title": "..."
},
...
]
}
```
Publishing the `More topics` super-topic is still to come.

Update topics when publishing an article

---

src/main/scala/managehelpcontentpublisher/Handler.scala
src/main/scala/managehelpcontentpublisher/Logging.scala

This change makes it easier to query and filter entries in Cloudwatch Insights.
Eg.
```
fields @timestamp, message
| filter event = 'Response' and code = 500
```
See https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData-discoverable-fields.html.

Log entries as Json objects rather than strings

---

src/main/scala/managehelpcontentpublisher/Config.scala
src/main/scala/managehelpcontentpublisher/Eithers.scala
src/main/scala/managehelpcontentpublisher/Handler.scala
src/main/scala/managehelpcontentpublisher/MoreTopics.scala
src/main/scala/managehelpcontentpublisher/PathAndContent.scala
src/main/scala/managehelpcontentpublisher/S3.scala
src/main/scala/managehelpcontentpublisher/Topic.scala
src/test/scala/managehelpcontentpublisher/PathAndContentTestSuite.scala

We have a '[More topics](https://github.com/guardian/manage-help-content-publisher/compare/kc-more-topics?expand=1#diff-1d0bf09b6013ac73a4f0d92c285717b5cb83feb485f23a222f472f1119f89df9R8)' topic which is a compilation of all the published articles by topic in the non-[core](https://github.com/guardian/manage-help-content-publisher/compare/kc-more-topics?expand=1#diff-12a1907d64e37d3a23feef5d4d336d09f522325dc3d91fbf3c3ce2867be1731dR23-R30) topics.
This PR creates or updates the More topics list when an article is published.  It does this by [taking the existing list, if any, and overwriting any topics in it to which the published article belongs](https://github.com/guardian/manage-help-content-publisher/compare/kc-more-topics?expand=1#diff-1d0bf09b6013ac73a4f0d92c285717b5cb83feb485f23a222f4 …

Publish 'More topics' list

---

src/main/scala/managehelpcontentpublisher/Article.scala
src/main/scala/managehelpcontentpublisher/Handler.scala
src/main/scala/managehelpcontentpublisher/PathAndContent.scala
src/main/scala/managehelpcontentpublisher/S3.scala
src/main/scala/managehelpcontentpublisher/Topic.scala
src/test/scala/managehelpcontentpublisher/ArticleTopicTest.scala
src/test/scala/managehelpcontentpublisher/PathAndContentTestSuite.scala

This removes articles from topic pages when necessary.
It does this by:
1. [searching for the previous version of the article](https://github.com/guardian/manage-help-content-publisher/compare/kc-article-change?expand=1#diff-db09425e7d17a397436623627dbbc7263593c7c21d5cc87a63ef7a59b4d5ce31R109), if any,
1. [comparing topics of the new version of the article with the topics of the previous published version](https://github.com/guardian/manage-help-content-publisher/compare/kc-article-change?expand=1#diff-36c0765d203a09eda21d13651ff790fbf66bda6d199e2df673c55be291255d1fR34-R35),
1. [removing the article from the topic it no longer appears in](https://github.com/guardian/manage-help-content-publisher/compare/kc-article-change?expand=1#diff-db09425e7d17a397436623627dbbc7263593c7c21d5cc87a63ef7a5 …

When a topic is removed from an article, republish the topic page without the article

---

src/main/scala/managehelpcontentpublisher/MoreTopics.scala
src/main/scala/managehelpcontentpublisher/PathAndContent.scala
src/test/scala/managehelpcontentpublisher/MoreTopicsTest.scala
src/test/scala/managehelpcontentpublisher/PathAndContentTestSuite.scala

When a non-core topic is removed from an article, republish the 'More topics' page without the article.
The key step is, before adding new topics to the 'More topics' page, we [remove the article from the lists it was in previously](https://github.com/guardian/manage-help-content-publisher/compare/kc-no-more-topics?expand=1#diff-1d0bf09b6013ac73a4f0d92c285717b5cb83feb485f23a222f472f1119f89df9R33-R34).

Remove redundant articles from 'More topics' page

---

build.sbt
project/plugins.sbt
src/main/scala/managehelpcontentpublisher/Logging.scala

This helps us to understand where we are by adding the Teamcity build number, or whichever build number Riffraff uses, to  Cloudwatch log entries.
Entries now appear like this:
`{"build":"80","logLevel":"INFO","event":"Request","body":"...`

Add build number to log entries

---

build.sbt

`in` => `/`
See:
https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+to+slash+syntax

Refactor to avoid SBT warning

---

.scalafmt.conf
cfn.yaml
riff-raff.yaml
src/main/scala/managehelpcontentpublisher/Article.scala
src/main/scala/managehelpcontentpublisher/Eithers.scala
src/main/scala/managehelpcontentpublisher/Failure.scala
src/main/scala/managehelpcontentpublisher/Handler.scala
src/main/scala/managehelpcontentpublisher/InputModel.scala
src/main/scala/managehelpcontentpublisher/Logging.scala
src/main/scala/managehelpcontentpublisher/MoreTopics.scala
src/main/scala/managehelpcontentpublisher/PathAndContent.scala
src/main/scala/managehelpcontentpublisher/PublishingHandler.scala
src/main/scala/managehelpcontentpublisher/S3.scala
src/main/scala/managehelpcontentpublisher/TakingDownHandler.scala
src/main/scala/managehelpcontentpublisher/Topic.scala
src/test/scala/managehelpcontentpublisher/MoreTopicsTest.scala
src/test/scala/managehelpcontentpublisher/PathAndContentTestSuite.scala

This change adds an [endpoint to the publisher to make takedown requests](https://github.com/guardian/manage-help-content-publisher/compare/kc-takedown?expand=1#diff-fa38c37d169b2fe9b07d85161af66c2ffe555173b5b6dad88ae3884e4e7e0410R115-R116).
To take down an article, we:
1. [re-publish topic pages omitting the article](https://github.com/guardian/manage-help-content-publisher/compare/kc-takedown?expand=1#diff-db09425e7d17a397436623627dbbc7263593c7c21d5cc87a63ef7a59b4d5ce31R132)
1. [re-publish the more topics page omitting the article](https://github.com/guardian/manage-help-content-publisher/compare/kc-takedown?expand=1#diff-db09425e7d17a397436623627dbbc7263593c7c21d5cc87a63ef7a59b4d5ce31R133)
1. [delete the article](https://github.com/guardian/manage-help-content-publisher/compare/kc-taked …

Support taking down articles

---

cfn.yaml

So that the lambdas can continue to read from a private bucket.

Give permission to read from membership-dist

---

build.sbt
src/main/scala/managehelpcontentpublisher/Config.scala
src/main/scala/managehelpcontentpublisher/PathAndContent.scala
src/main/scala/managehelpcontentpublisher/PublishingOps.scala
src/main/scala/managehelpcontentpublisher/S3.scala
src/test/resources/sitemap.txt
src/test/scala/managehelpcontentpublisher/PathAndContentTestSuite.scala

In this context, a sitemap is just considered to be a set of URLs that we want bots to index.  So specifically it's going to be a list of article URLs.
When an article is published or re-published, we check the sitemap to see if the article is already in the list.  If it isn't there, we add it.
This has been tested in the Dev stage.
In another PR, we will ping Google whenever an article is published, regardless of whether the sitemap has changed, so that it will reindex the content.
See:
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap

Update sitemap when an article is published

---

src/main/scala/managehelpcontentpublisher/PathAndContent.scala
src/test/resources/articles/changing-my-contribution-amount.json
src/test/resources/sitemap.txt
src/test/resources/topics/apps.json
src/test/resources/topics/more-topics.json
src/test/scala/managehelpcontentpublisher/PathAndContentTestSuite.scala

As part of the [taking-down process](https://github.com/guardian/manage-help-content-publisher/compare/kc-sitemap?expand=1#diff-db09425e7d17a397436623627dbbc7263593c7c21d5cc87a63ef7a59b4d5ce31R123-R145), we [remove the article from the sitemap](https://github.com/guardian/manage-help-content-publisher/compare/kc-sitemap?expand=1#diff-db09425e7d17a397436623627dbbc7263593c7c21d5cc87a63ef7a59b4d5ce31R125-R131).
The rest of this change is test code.
See also #114

Remove article from sitemap on takedown

---

src/main/scala/managehelpcontentpublisher/HtmlToJson.scala
src/test/scala/managehelpcontentpublisher/HtmlToJsonTestSuite.scala

There were problems when a paragraph contained a line-break and a non-block element, such as an anchor element.
We do a naive transformation before beginning, which nudges the HTML block into the right form for further processing.

Convert line-breaks from HTML to Json correctly

---

src/main/scala/managehelpcontentpublisher/Config.scala
src/main/scala/managehelpcontentpublisher/PathAndContent.scala

According to the [sitemaps documentation](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#addsitemap), we should ping Google whenever the sitemap changes.
This change does that whenever an article is added to, or removed from, the list.
It's in draft until we're ready to start having the content indexed in search engines.

Ping Google when the sitemap changes

---

.github/workflows/ci.yml
.gitignore
build.sbt
cfn.yaml
project/plugins.sbt
riff-raff.yaml
src/main/scala/managehelpcontentpublisher/Logging.scala

This PR sets up CI using GitHub Actions. It's now using the [Riff-Raff upload action](https://github.com/guardian/actions-riff-raff), and the deprecated `riffRaffUpload` plugin has been removed.

Configure GitHub Actions CI

---

.github/workflows/snyk.yml

We discovered that since this PR https://github.com/guardian/manage-help-content-publisher/pull/474 we had a very strange project name ending in `_213`
so I did this PR https://github.com/guardian/.github/pull/71
which made it more like the happy face 
This PR makes the snyk step use the new name, but we have to wait for the above PR to merge and switch back to the `main` branch again before merging this one.  Then we can do similar PRs in other repos.

make snyk monitor use a better project name

---

.github/workflows/ci.yml
.tool-versions

Uses the Guardian-provided [setup-scala](https://github.com/guardian/setup-scala) workflow to avoid `sbt: command not found` errors during CI builds (caused by github no longer rolling sbt with java).

Use GU setup-scala workflow
